replicaCount: 3

chaoskube:
  args:
    interval: "15m"
    kinds: "!DaemonSet"
    namespaces: "!kube-system"
    excluded-times-of-day: "18:00-09:00,14:15-16:00"
    timezone: "Europe/London"
    no-dry-run: ""
    
resources:
  limits:
    cpu: 30m
    memory: 48Mi
  requests:
    cpu: 30m
    memory: 48Mi