replicas: 3

args:
  - --kubelet-insecure-tls
  - --kubelet-preferred-address-types=InternalIP 
  - --metric-resolution=10s

podDisruptionBudget:
  enabled: true
  minAvailable: 1

resources:
  requests:
    cpu: 100m
    memory: 200Mi