controller:
  replicaCount: 3

  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 11
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 70

  ingressClassResource:
    name: nginx-production

  service:
    annotations:
      "service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https": "true"

  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 128Mi