controller:
  replicaCount: 3

  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 5

  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 128Mi