controller:
  replicaCount: 3

  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 70

  ingressClassResource:
    name: nginx-staging

  # service:
    # annotations: {}
      # "service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https": "true"

  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 300m
      memory: 128Mi

  labels:
    distribute: "true"