---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: allowed-podpriorities
  annotations:
    pod-policies.kyverno.io/autogen-controllers: DaemonSet,Deployment,Job,StatefulSet,CronJob
    policies.kyverno.io/title: Allowed Pod Priorities
    policies.kyverno.io/category: Sample
    policies.kyverno.io/minversion: 1.3.0
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      A pod priority class is only allowed to be set if in the allowed-priority-classes configmap in the default namespace
spec:
  validationFailureAction: audit
  background: false
  rules:
  - name: validate-pod-priority
    context:
      - name: podprioritydict
        configMap:
          name: allowed-priority-classes
          namespace: default
    match:
      resources:
        kinds:
        - Pod
    validate:
      message: >-
        The Pod PriorityClass {{ request.object.spec.priorityClassName }} is not in the list
        of the following PriorityClasses allowed: {{ podprioritydict.data }}.        
      deny:
        conditions:
        - key: "{{ request.object.spec.priorityClassName }}"
          operator: NotIn
          value:  "{{ podprioritydict.data }}"